In [4]:
!pip install numpy pandas

Requirement already satisfied: numpy in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (2.4.4)
Requirement already satisfied: pandas in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import numpy as np

In [4]:
print("hello")

hello

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv('Salaries - Salaries.csv')
print(df.loc[df["TotalPay"] > 300000 , 'EmployeeName'] )
print(df.describe())

df.head().to_csv('topFive.csv')
df.describe().to_csv('described.csv')

0             NATHANIEL FORD
1               GARY JIMENEZ
2             ALBERT PARDINI
3          CHRISTOPHER CHONG
4            PATRICK GARDNER
                 ...
110540      David L Franklin
110542           Yifang Qian
110543     Richard L Corriea
110545           Jose L Velo
110546    Bryan W Rubenstein
Name: EmployeeName, Length: 61, dtype: str
                  Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000
mean    74327.500000   66325.448840    5066.059886    3648.767297
std     42912.857795   42764.635495   11454.380559    8056.601866
min         1.000000    -166.010000      -0.010000   -7058.590000
25%     37164.250000   33588.200000       0.000000       0.000000
50%     74327.500000   65007.450000       0.000000     811.270000
75%    111490.750000   94691.050000    4658.175000    4236.065000
max    148654.000000  319275.010000  245131.880000  400184.250000

            TotalPay  TotalPayBenefits           Year
count  148654.000000     148654.000000  148654.000000
mean    74768.321972      93692.554811    2012.522643
std     50517.005274      62793.533483       1.117538
min      -618.130000       -618.130000    2011.000000
25%     36168.995000      44065.650000    2012.000000
50%     71426.610000      92404.090000    2013.000000
75%    105839.135000     132876.450000    2014.000000
max    567595.430000     567595.430000    2014.000000

In [7]:
df['BasePay'].isnull()

0         False
1         False
2         False
3         False
4         False
          ...
148649    False
148650     True
148651     True
148652     True
148653    False
Name: BasePay, Length: 148654, dtype: bool

In [ ]:
df.iloc[df['EmployeeName'] == '']

Empty DataFrame
Columns: [Id, EmployeeName, JobTitle, BasePay, OvertimePay, OtherPay, TotalPay, TotalPayBenefits, Year]
Index: []

In [10]:
print(df.iloc[df['EmployeeName'] == 'NATHANIEL FORD'])

   Id    EmployeeName                                        JobTitle  \
0   1  NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY

     BasePay  OvertimePay   OtherPay   TotalPay  TotalPayBenefits  Year
0  167411.18          0.0  400184.25  567595.43         567595.43  2011

In [11]:
df.iloc[df['EmployeeName'] == 'NATHANIEL FORD']

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,TotalPay,TotalPayBenefits,Year
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,567595.43,567595.43,2011